# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/pantech/ef63/setup-makefiles.sh

#IM-A910L
PRODUCT_COPY_FILES += \
    vendor/pantech/ef63/proprietary/vendor/etc/firmware_ef63l/venus.mbn:system/vendor/etc/firmware_ef63l/venus.mbn \
    vendor/pantech/ef63/proprietary/vendor/etc/firmware_ef63l/venus.mdt:system/vendor/etc/firmware_ef63l/venus.mdt \
    vendor/pantech/ef63/proprietary/vendor/etc/firmware_ef63l/venus.b00:system/vendor/etc/firmware_ef63l/venus.b00 \
    vendor/pantech/ef63/proprietary/vendor/etc/firmware_ef63l/venus.b01:system/vendor/etc/firmware_ef63l/venus.b01 

#IM-A910S
PRODUCT_COPY_FILES += \
    vendor/pantech/ef63/proprietary/vendor/etc/firmware_ef63s/venus.mbn:system/vendor/etc/firmware_ef63s/venus.mbn \
    vendor/pantech/ef63/proprietary/vendor/etc/firmware_ef63s/venus.mdt:system/vendor/etc/firmware_ef63s/venus.mdt \
    vendor/pantech/ef63/proprietary/vendor/etc/firmware_ef63s/venus.b00:system/vendor/etc/firmware_ef63s/venus.b00 \
    vendor/pantech/ef63/proprietary/vendor/etc/firmware_ef63s/venus.b01:system/vendor/etc/firmware_ef63s/venus.b01 

#IM-A910K
PRODUCT_COPY_FILES += \
    vendor/pantech/ef63/proprietary/vendor/etc/firmware_ef63k/venus.mbn:system/vendor/etc/firmware_ef63k/venus.mbn \
    vendor/pantech/ef63/proprietary/vendor/etc/firmware_ef63k/venus.mdt:system/vendor/etc/firmware_ef63k/venus.mdt \
    vendor/pantech/ef63/proprietary/vendor/etc/firmware_ef63k/venus.b00:system/vendor/etc/firmware_ef63k/venus.b00 \
    vendor/pantech/ef63/proprietary/vendor/etc/firmware_ef63k/venus.b01:system/vendor/etc/firmware_ef63k/venus.b01 

PRODUCT_COPY_FILES += \
    vendor/pantech/ef63/proprietary/vendor/bin/sensors.qcom:system/vendor/bin/sensors.qcom \
    vendor/pantech/ef63/proprietary/vendor/etc/firmware/venus.b02:system/vendor/firmware/venus.b02 \
    vendor/pantech/ef63/proprietary/vendor/etc/firmware/venus.b03:system/vendor/firmware/venus.b03 \
    vendor/pantech/ef63/proprietary/vendor/etc/firmware/venus.b04:system/vendor/firmware/venus.b04 \
    vendor/pantech/ef63/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    vendor/pantech/ef63/proprietary/lib/libmm-qcamera.so:system/lib/libmm-qcamera.so \
    vendor/pantech/ef63/proprietary/lib/libmmcamera_rohm_eeprom.so:system/lib/libmmcamera_rohm_eeprom.so \
    vendor/pantech/ef63/proprietary/lib/libmmcamera_rumba_sa_eeprom.so:system/lib/libmmcamera_rumba_sa_eeprom.so \
    vendor/pantech/ef63/proprietary/lib/libmmcamera_s5k6b2yx.so:system/lib/libmmcamera_s5k6b2yx.so \
    vendor/pantech/ef63/proprietary/lib/libsnsutils.so:system/lib/libsnsutils.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera_SKUAA_ST_gc0339.so:system/vendor/lib/libmmcamera_SKUAA_ST_gc0339.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera_SKUAB_ST_s5k4e1.so:system/vendor/lib/libmmcamera_SKUAB_ST_s5k4e1.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera_hi256.so:system/vendor/lib/libmmcamera_hi256.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera_imx134.so:system/vendor/lib/libmmcamera_imx134.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera_imx135.so:system/vendor/lib/libmmcamera_imx135.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera_imx214.so:system/vendor/lib/libmmcamera_imx214.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera_mt9m114.so:system/vendor/lib/libmmcamera_mt9m114.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so:system/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera_ov2720.so:system/vendor/lib/libmmcamera_ov2720.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera_ov5648_oty5f03.so:system/vendor/lib/libmmcamera_ov5648_oty5f03.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera_ov8825.so:system/vendor/lib/libmmcamera_ov8825.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera_ov8865_q8v18a.so:system/vendor/lib/libmmcamera_ov8865_q8v18a.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera_ov9724.so:system/vendor/lib/libmmcamera_ov9724.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera_s5k3l1yx.so:system/vendor/lib/libmmcamera_s5k3l1yx.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera_skuab_shinetech_gc0339.so:system/vendor/lib/libmmcamera_skuab_shinetech_gc0339.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera_skuf_ov12830_p12v01c.so:system/vendor/lib/libmmcamera_skuf_ov12830_p12v01c.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera_skuf_ov5648_p5v23c.so:system/vendor/lib/libmmcamera_skuf_ov5648_p5v23c.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera_sp1628.so:system/vendor/lib/libmmcamera_sp1628.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so:system/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so:system/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so:system/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
    vendor/pantech/ef63/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    vendor/pantech/ef63/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/pantech/ef63/proprietary/vendor/lib/hw/camera.msm8974.so:system/vendor/lib/hw/camera.msm8974.so
